export const START_MAIN_SCENE = 'START_MAIN_SCENE';
export const START_AUTHORIZATION_SCENE = 'START_AUTHORIZATION_SCENE';
export const START_QUIZ_SCENE = 'START_QUIZ_SCENE';
export const START_INTERVIEW_SCENE = 'START_INTERVIEW_SCENE';
export const GET_INFO_ABOUT_ME_SCENE = 'GET_INFO_ABOUT_ME_SCENE';
export const GET_MY_WRONG_ANSWERS_SCENE = 'GET_MY_WRONG_ANSWERS_SCENE';
export const SEND_HELP_SCENE = 'SEND_HELP_SCENE';
export const START_ADMINISTRATION_SCENE = 'START_ADMINISTRATION_SCENE';
export const EDIT_ADMINISTRATORS_SCENE = 'EDIT_ADMINISTRATORS_SCENE';
export const EDIT_QUESTIONS_SCENE = 'EDIT_QUESTIONS_SCENE';
export const EDIT_USERS_SCENE = 'EDIT_USERS_SCENE';
export const ADD_NEW_ADMINISTRATOR_SCENE = 'ADD_NEW_ADMINISTRATOR_SCENE';
export const DELETE_ADMINISTRATOR_SCENE = 'DELETE_ADMINISTRATOR_SCENE';
export const ADD_QUESTION_SCENE = 'ADD_QUESTION_SCENE';
export const DELETE_QUESTION_SCENE = 'DELETE_QUESTION_SCENE';
export const UPDATE_QUESTION_SCENE = 'UPDATE_QUESTION_SCENE';
//
export const ADD_QUESTION_CREATOR_SCENE = 'ADD_QUESTION_CREATOR_SCENE';
export const ADD_CORRECT_ANSWER_CREATOR_SCENE =
  'ADD_CORRECT_ANSWER_CREATOR_SCENE';
export const ADD_FIRST_WRONG_ANSWER_CREATOR_SCENE =
  'ADD_FIRST_WRONG_ANSWER_CREATOR_SCENE';
export const ADD_SECOND_WRONG_ANSWER_CREATOR_SCENE =
  'ADD_SECOND_WRONG_ANSWER_CREATOR_SCENE';
export const ADD_THIRD_WRONG_ANSWER_CREATOR_SCENE =
  'ADD_THIRD_WRONG_ANSWER_CREATOR_SCENE';
//
export const CHANGE_QUESTION_ADMIN_SCENE = 'CHANGE_QUESTION_ADMIN_SCENE';
export const CHANGE_CORRECT_ANSWER_ADMIN_SCENE =
  'CHANGE_CORRECT_ANSWER_ADMIN_SCENE';
export const CHANGE_FIRST_ANSWER_ADMIN_SCENE =
  'CHANGE_FIRST_ANSWER_ADMIN_SCENE';
export const CHANGE_SECOND_ANSWER_ADMIN_SCENE =
  'CHANGE_SECOND_ANSWER_ADMIN_SCENE';
export const CHANGE_THIRD_ANSWER_ADMIN_SCENE =
  'CHANGE_THIRD_ANSWER_ADMIN_SCENE';
//
export const BAN_USER_SCENE = 'BAN_USER_SCENE';
export const UNBAN_USER_SCENE = 'UNBAN_USER_SCENE';
